### ISSUE TITLE
make jumplines draggable

### ISSUE THREAD

**Issue by bwl21** [bwl21/zupfnoter#136]
# Request

* configuration of Jumpline, in particular the vertical position is not very intutiive
* if a variant end starts with a repetition end, it cannot be properly configured.

# Solution approach

* migrate from Addon to a regular configuration
* let the configuration override the Addon
* add a handle to the vertical part of jumpline to drag

```javascript
{
'notebound': {
        'jumplines' :{
              'v_1' : {
                       't_2134': {'pos_r': 1},
                       't_2134' {'pos_in': 1, 'pos_o': 2, 'pos_f': 3},
                      }
              }
     }
}
```

# todo

- [x] decide the configuration
- [x] implement a draggable_jumpline()
- [x] make computation of jumpline path a static method such that it is available in dragmove handler

# open

- [ ] move the computation of the new config-value out of on_annotation_drag_end?
